### ISSUE TITLE
Can't push app on newer buildpack

### ISSUE THREAD

**Issue by corymetter** [pacphi/cf-butler#139]
When I try to push the app after building, i get a "No compatible attachment provider is available" error message. It looks like the app is trying to start with JDK and not JRE. In the newer buildpacks, the JDK has been removed. Is there any tricks available to run this on JRE instead of JDK?

`2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 2019-12-11T20:52:49,852 ERROR [main] o.s.b.SpringApplication: Application run failed
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT java.lang.IllegalStateException: No compatible attachment provider is available
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:389)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:374)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:342)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:328)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at reactor.tools.agent.ReactorDebugAgent.init(ReactorDebugAgent.java:41)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.reactor.DebugAgentEnvironmentPostProcessor.postProcessEnvironment(DebugAgentEnvironmentPostProcessor.java:49)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:188)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:176)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at io.pivotal.cfapp.AppInit.main(AppInit.java:17)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
   2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)`

**Comment by fastnsilver** [comment]
Are you relying on auto-detection of buildpack? Would help if I knew which buildpack and version you are targeting.

**Comment by pacphi** [comment]
I just built and successfully pushed the latest from master to a foundation with the latest available Java buildpack installed (i.e., https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.26 as of today, 2019-12/16).

**Comment by pacphi** [comment]
If you're going the [Cloud Native Buildpack](https://buildpacks.io/docs/app-developer-guide/build-an-app/) route to produce an image, use...

```
pack suggested-builders
pack build cf-butler --builder cloudfoundry/cnb:bionic
```

**Comment by pacphi** [comment]
Lastly, if you're having trouble building yourself, you could pull a pre-built [release](https://jitpack.io/#pacphi/cf-butler) from jitpack.io.

**Comment by pacphi** [comment]
This caught my eye in your log output...

```
2019-12-11T14:52:49.86-0600 [APP/PROC/WEB/0] OUT at reactor.tools.agent.ReactorDebugAgent.init(ReactorDebugAgent.java:41) 2019-12-11T14:52:49.86-0600
```

Looks like you are trying to use `ReactorDebugAgent` from `reactor-tools`.  I wouldn't recommend that just yet.  I recommend trying to build again with the latest from master or pick up the `b20191216.1` release from jitpack.
