### ISSUE TITLE
Cannot read CF_TOKEN_PROVIDER property at startup

### ISSUE THREAD

**Issue by pacphi** [pacphi/cf-butler#185]
Deploying the latest from master (https://github.com/pacphi/cf-butler/commit/f5737740312a9abf8dc6dad1276b7e3b235d9e0d) to Cloud Foundry results in a startup issue.  

I've looked into [ButlerConfig.java](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/config/ButlerConfig.java#L42), [application.yml](https://github.com/pacphi/cf-butler/blob/master/src/main/resources/application.yml#L167), and my own copy of `secrets.json` for anything amiss (e.g., spurious bad characters, tabs instead of spaces), but nothing stands out as problematic on first-glance.

Here's what I see when consulting `cf logs cf-butler --recent`

```
2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT 2020-03-07T17:19:24,020 ERROR [main] o.s.b.SpringApplication: Application run failed
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT java.lang.IllegalStateException: Error processing condition on io.pivotal.cfapp.config.ButlerConfig.tokenProvider
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:184)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at io.pivotal.cfapp.AppInit.main(AppInit.java:18)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.services.cf-butler-secrets.credentials.CF_TOKEN_PROVIDER' in value "${vcap.services.cf-butler-secrets.credentials.CF_TOKEN_PROVIDER}"
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:88)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:62)
   2020-03-07T09:19:24.02-0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
   2020-03-07T09:19:24.08-0800 [CELL/SSHD/0] OUT Exit status 0
```

**Comment by pacphi** [comment]
Resolved as of https://github.com/pacphi/cf-butler/commit/8c1b690e7c21cdea35a2865138d83fac7cc3e3fe.
