### ISSUE TITLE
Ops manager endpoints running into cert issues

### ISSUE THREAD

**Issue by 505042436** [pacphi/cf-butler#389]
When i enable the ops manger endpoints usage and access them i see in the logs that its running into cert issue. I checked the https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/config/ButlerCfEnvProcessor.java but seems like there is no mapping for skipping ssl validation for OM api calls.

**Comment by pacphi** [comment]
OpsmanAccessTokenProvider uses the WebClient instance that was configured here: https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/config/WebClientConfig.java. So if you set the conditional property to true it should also allow for Opsman insecure access.

**Comment by pacphi** [comment]
What versions of Opsman and Tanzu Application Service are you running?

**Comment by 505042436** [comment]
we are using  v2.10.16. I made the change to application.yml to include sslValidationSkipped to true but still running into same error

 2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at java.base/sun.security.validator.Validator.validate(Unknown Source)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.security.FileWatchingX509ExtendedTrustManager.checkServerTrusted(FileWatchingX509ExtendedTrustManager.java:73)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.security.DelegatingX509ExtendedTrustManager$6.accept(DelegatingX509ExtendedTrustManager.java:102)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.security.DelegatingX509ExtendedTrustManager.with(DelegatingX509ExtendedTrustManager.java:143)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.security.DelegatingX509ExtendedTrustManager.checkServerTrusted(DelegatingX509ExtendedTrustManager.java:98)
   2021-09-15T21:39:38.03+0000 [APP/PROC/WEB/0] OUT     at java.base/su

**Comment by pacphi** [comment]
That is the design constraint here, that both APIs utilize the same WebClient and auth scheme.  The only two schemes supported are "client_credentials" and "password".  See https://docs.cloudfoundry.org/api/uaa/version/4.35.0/index.html#token.
