### ISSUE TITLE
Decoding issue with java.sql.Timestamp using Postgresql R2DBC

### ISSUE THREAD

**Issue by lerytke** [pacphi/cf-butler#39]
I am using the CF admin account, but I see in the logs saying it can't get a token from UAA

2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] [30m2019-06-03T13:03:11,037[m [1;31mERROR [m[[1;34mreactor-tcp-epoll-1[m] [1;33mo.s.c.l.CompositeLog[m: [08a2e87f] 500 Server Error for HTTP GET "/snapshot/spaces/users"
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] java.lang.IllegalArgumentException: Cannot decode value of type java.sql.Timestamp
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:97)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:88)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.pivotal.cfapp.repository.R2dbcTkRepository.fromRow(R2dbcTkRepository.java:45)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.pivotal.cfapp.repository.R2dbcTkRepository.lambda$findOne$0(R2dbcTkRepository.java:40)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.r2dbc.postgresql.PostgresqlResult.lambda$map$0(PostgresqlResult.java:71)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxZip$ZipCoordinator.drain(FluxZip.java:735)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxZip$ZipInner.onNext(FluxZip.java:894)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:78)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1510)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:389)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onComplete(FluxFilterFuseable.java:166)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxReplay$UnboundedReplayBuffer.replayNormal(FluxReplay.java:550)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxReplay$UnboundedReplayBuffer.replay(FluxReplay.java:653)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxReplay$ReplaySubscriber.onComplete(FluxReplay.java:1188)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxTake$TakeSubscriber.onComplete(FluxTake.java:147)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxTake$TakeSubscriber.onNext(FluxTake.java:127)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:422)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:264)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxHide$HideSubscriber.onNext(FluxHide.java:74)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:180)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:636)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:714)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:756)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:227)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:238)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:248)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:113)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:320)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:826)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:275)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:849)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxGenerate$GenerateSubscription.next(FluxGenerate.java:169)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.r2dbc.postgresql.message.backend.BackendMessageDecoder.lambda$decode$1(BackendMessageDecoder.java:82)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:262)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:204)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1874)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1748)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:83)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.Flux.subscribe(Flux.java:7799)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:442)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:244)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:206)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:322)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:335)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:432)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2019-06-03T09:03:11.038-04:00 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.Thread.run(Unknown Source)
2019-06-03T09:03:11.043-04:00 [RTR/1] [OUT] cf-butler-responsible-genet.dev.dev.east.paas.geointservices.io - [2019-06-03T13:03:11.031+0000] "GET /snapshot/spaces/users HTTP/1.1" 500 0 180 "-" "PostmanRuntime/7.13.0" "10.104.96.7:28910" "10.104.98.222:61022" x_forwarded_for:"70.167.241.178, 10.104.96.7" x_forwarded_proto:"https" vcap_request_id:"d9b11113-fd21-4db4-57b2-188e2f25bcc5" response_time:0.011171557 app_id:"5719baea-86b4-4046-801c-5b26b51d954f" app_index:"0" nga:"-" pcf:"-" x_b3_traceid:"cd9bb8ec138d6598" x_b3_spanid:"cd9bb8ec138d6598" x_b3_parentspanid:"-"
2019-06-03T09:03:35.745-04:00 [RTR/2] [OUT] cf-butler-responsible-genet.dev.dev.east.paas.geointservices.io - [2019-06-03T13:03:35.739+0000] "OPTIONS /cloudfoundryapplication/health HTTP/1.1" 200 0 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "10.104.96.7:1764" "10.104.98.222:61022" x_forwarded_for:"70.167.241.178, 10.104.96.7" x_forwarded_proto:"https" vcap_request_id:"90d6527c-cb81-4d59-4ccd-87c5a08ad1e9" response_time:0.005906697 app_id:"5719baea-86b4-4046-801c-5b26b51d954f" app_index:"0" nga:"-" pcf:"-" x_b3_traceid:"962bddeb40bf456a" x_b3_spanid:"962bddeb40bf456a" x_b3_parentspanid:"-"
2019-06-03T09:03:35.745-04:00 [RTR/0] [OUT] cf-butler-responsible-genet.dev.dev.east.paas.geointservices.io - [2019-06-03T13:03:35.740+0000] "OPTIONS /cloudfoundryapplication/info HTTP/1.1" 200 0 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "10.104.96.7:61626" "10.104.98.222:61022" x_forwarded_for:"70.167.241.178, 10.104.96.7" x_forwarded_proto:"https" vcap_request_id:"41d39fdc-d155-40fa-5e92-7c45db09cac8" response_time:0.004362136 app_id:"5719baea-86b4-4046-801c-5b26b51d954f" app_index:"0" nga:"-" pcf:"-" x_b3_traceid:"782cda88b7439b1b" x_b3_spanid:"782cda88b7439b1b" x_b3_parentspanid:"-"
2019-06-03T09:03:35.747-04:00 [RTR/1] [OUT] cf-butler-responsible-genet.dev.dev.east.paas.geointservices.io - [2019-06-03T13:03:35.742+0000] "OPTIONS /cloudfoundryapplication/mappings HTTP/1.1" 200 0 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "10.104.96.7:28030" "10.104.98.222:61022" x_forwarded_for:"70.167.241.178, 10.104.96.7" x_forwarded_proto:"https" vcap_request_id:"6c8669b4-fab6-4811-77b2-ecf0a76ca472" response_time:0.004907145 app_id:"5719baea-86b4-4046-801c-5b26b51d954f" app_index:"0" nga:"-" pcf:"-" x_b3_traceid:"1cc6ab469a11e3d8" x_b3_spanid:"1cc6ab469a11e3d8" x_b3_parentspanid:"-"
2019-06-03T09:03:35.792-04:00 [RTR/0] [OUT] cf-butler-responsible-genet.dev.dev.east.paas.geointservices.io - [2019-06-03T13:03:35.761+0000] "GET /cloudfoundryapplication/mappings HTTP/1.1" 200 0 50798 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "10.104.96.7:61626" "10.104.98.222:61022" x_forwarded_for:"70.167.241.178, 10.104.96.7" x_forwarded_proto:"https" vcap_request_id:"6aabf72e-d2f2-4894-6241-143cca85a089" response_time:0.030318053 app_id:"5719baea-86b4-4046-801c-5b26b51d954f" app_index:"0" nga:"-" pcf:"-" x_b3_traceid:"e5a035caf7bc11f5" x_b3_spanid:"e5a035caf7bc11f5" x_b3_parentspanid:"-"
2019-06-03T09:03:35.796-04:00 [RTR/2] [OUT] cf-butler-responsible-genet.dev.dev.east.paas.geointservices.io - [2019-06-03T13:03:35.766+0000] "GET /cloudfoundryapplication/info HTTP/1.1" 200 0 84 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "10.104.96.7:1764" "10.104.98.222:61022" x_forwarded_for:"70.167.241.178, 10.104.96.7" x_forwarded_proto:"https" vcap_request_id:"f7ca66ba-980e-4757-7ae2-7bdd02261fc4" response_time:0.030357352 app_id:"5719baea-86b4-4046-801c-5b26b51d954f" app_index:"0" nga:"-" pcf:"-" x_b3_traceid:"dc9b54afe6faf9e2" x_b3_spanid:"dc9b54afe6faf9e2" x_b3_parentspanid:"-"
2019-06-03T09:03:35.815-04:00 [RTR/1] [OUT] cf-butler-responsible-genet.dev.dev.east.paas.geointservices.io - [2019-06-03T13:03:35.772+0000] "GET /cloudfoundryapplication/health HTTP/1.1" 200 0 192 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "10.104.96.7:28958" "10.104.98.222:61022" x_forwarded_for:"70.167.241.178, 10.104.96.7" x_forwarded_proto:"https" vcap_request_id:"1fc9e94a-b5a5-42f4-773f-f257c6d30861" response_time:0.043300277 app_id:"5719baea-86b4-4046-801c-5b26b51d954f" app_index:"0" nga:"-" pcf:"-" x_b3_traceid:"9c10dec6c3d7408d" x_b3_spanid:"9c10dec6c3d7408d" x_b3_parentspanid:"-"

and from the api it says

{
"timestamp": "2019-05-30T20:46:44.390+0000",
"path": "/snapshot/spaces/users",
"status": 500,
"error": "Internal Server Error",
"message": "Cannot decode value of type java.sql.Timestamp"
}

**Comment by pacphi** [comment]
`io.r2dbc.postgresql.codec.DateCodec` does not appear to have support for `java.sql.Timestamp`.  I'm working on an update to work directly with `java.time.LocalDateTime` and `java.time.LocalDate`.  I've also consulted `io.r2dbc.h2.codecs.DateCodec` to see if it has like support for work with these types, and it does.

**Comment by lerytke** [comment]
thanks

**Comment by pacphi** [comment]
So the fix 6190efc uncovers another issue reported here: https://github.com/r2dbc/r2dbc-h2/issues/78.  I may have to "hack in" a temporary fix until that is resolved.

**Comment by pacphi** [comment]
@lerytke I believe I've taken care of this with updates in 9298778e19c1148d7a8ba81c72e599af49dfe950. Please pull from this commit and try on your end. If it works for you, I'll merge this [PR](https://github.com/pacphi/cf-butler/pull/40).
