### ISSUE TITLE
In the Snapshot Detail AI report , the buildpack version doesn't reflect the real buildpack version used by the application

### ISSUE THREAD

**Issue by erboucherie** [pacphi/cf-butler#390]
Hello @pacphi , we 've found an issue with the buildpack version shown in the detail/Ai report .
This version is the version of the current buildpack provided by the platform .
But the real buildpack version used by the application is inside the current droplet object and can be different if the application has not been restaged since a Platform Buildpack upgrade .
There's a cf plugin  (`cf report-buildpack` )(https://github.com/govau/cf-report-buildpacks/blob/master/cmd/report-buildpacks/report-buildpacks.go) which gives the right info .
We wanted to use this detail/AI report to identify outdated buildpacks usage by running applications , to enforce them to restage .
Thanks again if you can have a look , knowing that this is a big change in the way to gather informations from the application .

Best regards
Eric

**Comment by pacphi** [comment]
This is indeed a very big change. 

I see https://v3-apidocs.cloudfoundry.org/version/3.107.0/index.html#get-a-droplet.  And I also see this inside the `cf-java-client`, https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/v3/applications/ReactorApplicationsV3.java#L117.

I experimented with invoking a method like the following and it's not returning what I'd expect... 

```
protected Mono<AppDetail> getBuildpackFromApplicationCurrentDroplet(AppDetail fragment) {
        log.trace("Fetching application current droplet buildpack for org={}, space={}, id={}, name={}", fragment.getOrganization(), fragment.getSpace(), fragment.getAppId(), fragment.getAppName());
        return opsClient
                .getCloudFoundryClient()
                .applicationsV3()
                .getCurrentDroplet(GetApplicationCurrentDropletRequest.builder().applicationId(fragment.getAppId()).build())
                .map(acd ->
                    AppDetail
                        .from(fragment)
                        .buildpack(acd.getBuildpacks() != null ? acd.getBuildpacks().stream().map(b -> b.getDetectOutput()).collect(Collectors.toList()).toString(): null)
                        .build()
                )
                .onErrorResume(ClientV3Exception.class, e -> Mono.just(fragment));
    }
```

I did that here

```
public void collect(List<Space> spaces) {
        log.info("AppDetailTask started");
        appDetailsService
            .deleteAll()
            .thenMany(Flux.fromIterable(spaces))
            .concatMap(this::listApplications)
            .flatMap(this::getSummaryInfo)
            .flatMap(this::getBuildpackFromApplicationCurrentDroplet)
            .flatMap(this::getStatistics)
            .flatMap(this::getLastEvent)
            .flatMap(appDetailsService::save)
            .thenMany(appDetailsService.findAll())
            .collectList()
            .subscribe(
                result -> {
                    publisher.publishEvent(new AppDetailRetrievedEvent(this).detail(result));
                    log.info("AppDetailTask completed");
                },
                error -> {
                    log.error("AppDetailTask terminated with error", error);
                }
            );
    }
```

I get output like

```
"[client-certificate-mapper=1.11.0_RELEASE container-security-provider=1.18.0_RELEASE java-buildpack=v4.33-offline-https://github.com/cloudfoundry/java-buildpack.git#dbec4b6 java-main java-opts java-security jvmkill-agent=1.16.0_REL... (no decorators apply)]"
```

I'd really **not** like to implement a custom service call to obtain the buildpack and version from the CF API.

[AppDetailTask](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/task/AppDetailTask.java) is where we'll have to spend time refactoring and testing.  

I welcome any help here.  Willing to look at PRs.

**Comment by pacphi** [comment]
The current method employed to obtain a buildpack and normalize the name relies on v2 CF API. See https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/task/AppDetailTask.java#L177.

**Comment by pacphi** [comment]
The fact that v3 CF API for the current application droplet may return a `List<Buildpack>` seems problematic.  Also, what should we persist for buildpack and version in AppDetail? I would think `buildpack_name` and `version`.

**Comment by erboucherie** [comment]
Yes the V3 cf api lists all the available droplets from latest deployments . The current droplet  is given by `/v3/apps/:guid/droplets/current` .
And agree to put the buildpacks information of that current droplet (buildpacks.name & buildpacks.version) in the AppDetail

**Comment by pacphi** [comment]
@erboucherie Try out this [branch ](https://github.com/pacphi/cf-butler/tree/issue-390) and let me know what you think. See the earlier commit reference above for what's been done so far.

**Comment by erboucherie** [comment]
@pacphi  thanks a lot for working on it so fast . It'll take me some time to test this version .
The first test i did (on our engineering Foundation) is not that good . I see `buildpack_version` set as the **latest** one whereas the field is empty in the droplet (due to too old droplets as you mentioned in the notes of your commit) .
I see other cases where your current droplet endpoint gives me a buildpackVersion different from the real one i see .

All my comparisons are done with the` cf curl /v3/apps/:guid/droplets/current` command line that i run  toward my foundation .
So it's currently difficult for me to say if that those inconsistencies come from your code , or directly from the V3 api you are using (org.cloudfoundry.client.v3.applications.GetApplicationCurrentDropletResponse) .

**Comment by erboucherie** [comment]
One more comment (nothing to see with this particular issue) , but when playing with the Json outputs of cf-butler , we've seen that most of the fields name contain **hyphen** , which is not well supported by jq filters (it assumes this is the `operator minus`) .
For instance this doesn't work : `/products/metrics |jq '.product-metrics[].name'` whereas this one work : `/products/metrics |jq '."product-metrics"[].name'`

But again , congratulations for all your work on this very helpful application

**Comment by pacphi** [comment]
The cf-java-client call to /v3/apps/:guid/droplets/current is made via https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/v3/applications/ReactorApplicationsV3.java#L117.  So it's the same call as you do with cf curl and should return the same result for the app guid.  I make that call in `AppDetailsTask` to override the buildpack name and version when an earlier call https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/v2/applications/ReactorApplicationsV2.java#L195 finds a `meta` buildpack.   I could adapt the filter and apply the override to apps where a buildpack was detected and in a running state.

What I've found with the aforementioned v3 API is that it doesn't do a great job returning the buildpack version for apps that are in stopped state.  I don't have access to a foundation with large footprint to be able to reason more about what I see.

**Comment by erboucherie** [comment]
On my side i didn't see misbehaviour on applications which are in `stopped `state . Your new endpoint has exactly the same output as the curl command . What is wrong is the output of the `/snapshot/detail` endpoint which doesn't match each individual `/apps/{guid}/droplets/current` endpoint .

**Comment by pacphi** [comment]
Ok. I pushed another update.  Look at the commit details.  I think this may result in what you're looking for.  Of note...

a) meta buildpacks are parsed
b) buildpack names are normalized

**Comment by erboucherie** [comment]
Yeah , you are almost done . Now the pb comes with the format of the java buildpacks version wich i must admit is a bit complicated (don't know why) .
For Java buildpack in the droplet object , we have :  
```
   "buildpacks": [
      {
         "name": "java_buildpack_offline",
         "detect_output": "java",
         "buildpack_name": "java",
         "version": "v4.34-offline-https://github.com/cloudfoundry/java-buildpack.git#04543c2"
      }
   ],
```
And with this format , we have an error when trying to store this value in the DB : 

```
Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column "buildpack_version VARCHAR(50)": "'v4.36-offline-https://github.com/cloudfoundry/java-buildpack.git#ebf9f057' (73)"; SQL statement:
INSERT INTO application_detail (organization, space, app_id, app_name, buildpack, buildpack_version, running_instances, total_instances, memory_used, disk_used, stack, urls, last_pushed, last_event_time, last_event, last_event_actor, requested_state, buildpack_release_type, buildpack_release_date, buildpack_latest_version, buildpack_latest_url) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21) [22001-200]
```
This on H2 DB running on my laptop , but i guess it would be the same error on any DB if the field is set with 50 cars .
Would it be an idea to parse the version ? But then it can become a pane to cope with all kind of versions depending on the different buildpacks .

**Comment by pacphi** [comment]
I would suggest we parse and strip after the second "-".  That accommodates "offline" buildpacks.  Or we normalize to just retain the version (e.g., v4.34 in your example above).

**Comment by pacphi** [comment]
Another [commit](https://github.com/pacphi/cf-butler/commit/95333fe3127016e123414bf8dbcf38f331c19b88).  Take another look?

**Comment by erboucherie** [comment]
Thanks so much . This one will take me some time to dig into , because  the AppDetail task fails with a parsing error : 
```
2021-09-30 08:20:15,967 ERROR [reactor-http-epoll-1] io.pivotal.cfapp.task.AppDetailTask: AppDetailTask terminated with error
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 6
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.MonoMapFuseable] :
        reactor.core.publisher.Mono.map(Mono.java:3354)
        io.pivotal.cfapp.task.AppDetailTask.getBuildpackFromApplicationCurrentDroplet(AppDetailTask.java:217)
Error has been observed at the following site(s):
        |_           Mono.map ⇢ at io.pivotal.cfapp.task.AppDetailTask.getBuildpackFromApplicationCurrentDroplet(AppDetailTask.java:217)
        |_ Mono.onErrorResume ⇢ at io.pivotal.cfapp.task.AppDetailTask.getBuildpackFromApplicationCurrentDroplet(AppDetailTask.java:218)
        |_       Flux.flatMap ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:98)
        |_       Flux.flatMap ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:99)
        |_       Flux.flatMap ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:100)
        |_       Flux.flatMap ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:101)
        |_      Flux.thenMany ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:102)
        |_      Flux.thenMany ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:102)
        |_   Flux.collectList ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:103)
Stack trace:
                at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
                at java.base/java.lang.String.substring(String.java:1874)
                at io.pivotal.cfapp.task.AppDetailTask.refineBuildpackFromApplicationCurrentDroplet(AppDetailTask.java:245)
```
I guess we are hitting some real life use cases , and that's always the hardest part of the Developer life to cope with exceptions .
One of them for instance is to have an application without current droplet . This is the case for one application in a stopped state (i even didn't know that this would be possible --> A Cloudfoundry bug probably) .
Let me check this error , and i'll come back to you asap .

**Comment by erboucherie** [comment]
Ok after some investigations , i found that it fails on droplet which buildpack is not java . In that case the version is basic : 
```
buildpacks: [
{
name: "python_buildpack",
detect_output: "python",
buildpack_name: "python",
version: "1.7.6"
}
]
```
or 
```
buildpacks: [
{
name: "staticfile_buildpack",
detect_output: "staticfile",
buildpack_name: "staticfile",
version: "1.5.1"
}
]
```
or 
```
buildpacks: [
{
name: "nodejs_buildpack",
detect_output: "nodejs",
buildpack_name: "nodejs",
version: "1.6.45"
}
]
```

**Comment by erboucherie** [comment]
Hello @pacphi , with the time difference between countries i just saw your update ths morning . I tested it , and indeed it's much better . 
I only saw one weird use case where the `/snapshot/detail `show a **null** version whereas the current droplet is good . I need to investigate on that specific case , but all other cases i checked are correct .
I guess i will be able to give you a **go** on that issue on **next monday** (will take me some times to test this update on all our foundations included Production ones) .
Thanks a lot again for all your work .
Best regards
Eric

**Comment by erboucherie** [comment]
One remark : At the starting phase , i see this warning : 
```
2021-10-01 09:43:04,893 INFO  [reactor-http-epoll-3] org.cloudfoundry.reactor.client.CloudFoundryClientCompatibilityChecker: Client supports API version 2.150.0 and is connected to server with API version 2.164.0. Things may not work as expected.
2
```
Where does the Client Supporting version is set ? Is that something you can drive ?
Thks

**Comment by pacphi** [comment]
Re: warning. That's the cf-Java-client library reporting it's support for interaction. I think I'm using one version behind the latest available. I will update to 5.6.0.  That said nothing within my control - the library authors are probably behind on full support for CF V3 API.

**Comment by erboucherie** [comment]
Hello @pacphi , it took me some time to understand the use cases where we still have the buildpack version set to null .
All of this happen when the `fragment.getBuildpack()` is Null in function **getBuildpackFromApplicationCurrentDroplet** (AppDetailTask.java) .
I tried to understand where and how this method is populated , but my Reactor skills are too low .
So to me , i would say that this version of code is sufficient for solving most of the general cases .
If you want me to test other commits don't hesitate . I'm glad to help you hardening this application .
